### ISSUE TITLE
Chests and signs light up when viewed at certain angles.

### ISSUE THREAD

**Issue by thaurane** [TheCBProject/ChickenChunks#64]
1.16.4-2.7.0.85-universal
forge 35.1.28

These objects light up as bright as possible when looking at certain angles. This started to appear immediately after I placed a chunk loader. Picking up the block stops the issue. The angle is somewhat in the direction of the chunk loader.
https://i.imgur.com/AMspr5G.png
https://i.imgur.com/OuMaGyJ.png

**Comment by thaurane** [comment]
Update: This is with using optifine HD_U_G5 "fast render: on

**Comment by covers1624** [comment]
Optifine is not supported and breaks mods. Remove optifine.

**Comment by thaurane** [comment]
The only other mod optifine has issues with is better portals (that I know of). Even then it is also fast render. I just won't bother to report any further issues if this is your stance on it.

**Comment by covers1624** [comment]
Optifine has aggressive changes across swaths of the Minecraft codebase. Optifine breaks mods, it has a very good history of this. I will not provide support for issues that happen only with Optifine installed, because as far as I'm concerned, ITS changes to the render pipeline are what's causing your issues.
